export declare function loaded(args: any): void;
export declare function cameraLoaded(args: any): void;
export declare function cancel(args: any): void;
export declare function takePhoto(args: any): void;
export declare function record(): void;
export declare function stopRecord(): void;
export declare function toggleFlash(): void;
export declare function toggleCamera(): void;
export declare function retry(args: any): void;
export declare function done(args: any): void;
